# This is a basic workflow to help you get started with Actions

name: run commands

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
    - name: My first step
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Chad
        MIDDLE_NAME: Michael
        LAST_NAME: Crowell
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
    - name: My second step
      if: success()
      run: echo "The previous step has finished successfully"
    - name: My third step
      uses: actions/checkout@v1
    - name: My fourth step
      uses: actions/setup-node@v1
    - name: my fifth step
      uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Message that will be displayed on users'' first issue'
        pr-message: 'Message that will be displayed on users'' first pr'
