name: build
on: 
  push:
    paths: 
      - '**.js'
jobs:
  build:
    name: my job
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: [10, 12, 14]
        exclude:
          - os: macos-latest
            node: 10
    steps:
      - uses: actions/checkout@v2
      - name: Use node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - name: Azure WebApp
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.APP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
  
