name: build
on: 
  push:
    paths: 
      - '**.js'
jobs:
  build:
    name: my job
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12.x]
        exclude:
          - os: macos-latest
            node: 10
    steps:
      - uses: actions/checkout@v2
      - name: Use node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: node index
      - name: Azure WebApp
        uses: Azure/webapps-deploy@v2
        with:
          app-name: node-hello-world99
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
  
